### ISSUE TITLE
UI bug (too lefty)

### ISSUE THREAD

**Issue by m0nk3ybraindead** [HuyaneMatsu/Koishi#15]
![Screenshot_20220218-212444](https://user-images.githubusercontent.com/77531972/154695016-0fc7b569-b98c-4fbf-8fa2-b086bede7f58.png)

**Comment by HuyaneMatsu** [comment]
Actually not lefty. The empty border is missing from both sides. This is indeed a bug tho.

**Comment by HuyaneMatsu** [comment]
Fixed min left and right spacing. Will be alive soon TM.

![Screenshot from 2022-02-20 09-48-39](https://user-images.githubusercontent.com/37266847/154835263-cd594405-8450-404f-8508-7069c292b84f.png)
