### ISSUE TITLE
Wrong image in guide

### ISSUE THREAD

**Issue by m0nk3ybraindead** [HuyaneMatsu/Koishi#16]
In the image we can see that the description says "turning all on for now" but it in the image it is actually turned off.
![Screenshot_20220218-213750](https://user-images.githubusercontent.com/77531972/154695230-cac9d05d-c2d0-4214-a9c3-72f529aea2f7.png)

**Comment by HuyaneMatsu** [comment]
Is this really a problem? if i would put there turned on, then that would be the problem...

I assume using a gif would solve the issue satisfying both sides.

**Comment by m0nk3ybraindead** [comment]
Oh yeh a gif would be a better idea!
