### ISSUE TITLE
Add "next" and "prev" button

### ISSUE THREAD

**Issue by m0nk3ybraindead** [HuyaneMatsu/Koishi#17]
While I was reading the docs and following the guide, I didn't know where to go next. It would be nice if there was a button here for continuous reading and developing. 

![Screenshot_20220218-214126](https://user-images.githubusercontent.com/77531972/154695607-9354be42-2787-4553-a26f-db30274938e3.png)

**Comment by HuyaneMatsu** [comment]
Added support for next up buttons.

![Screenshot from 2022-02-20 14-42-11](https://user-images.githubusercontent.com/37266847/154845524-8991b39e-b960-4f8e-9f25-3ff5275d24db.png)

I am not sure about "prev" buttons.

----

Will be alive soon TM.
