### ISSUE TITLE
Navigation colors

### ISSUE THREAD

**Issue by m0nk3ybraindead** [HuyaneMatsu/Koishi#18]
In here it's hard to read the text because the navigation text mixes up with the text behind. If this was darker it would be better for reading.
![Screenshot_20220218-213750](https://user-images.githubusercontent.com/77531972/154696352-08ed458d-89b4-439c-8c25-793317e8636f.png)

**Comment by HuyaneMatsu** [comment]
Exclusive preview of the new improved header opacity.

![Screenshot from 2022-03-05 13-35-01](https://user-images.githubusercontent.com/37266847/156883262-cc8ecc62-9850-4b0f-b650-efdff821100d.png)
