### ISSUE TITLE
Command desing: most used emojis

### ISSUE THREAD

**Issue by albertopoljak** [HuyaneMatsu/Koishi#23]
Few ideas for the most used emojis command that might improve design:

1. 

When used on specific user emojis will be shown in columns, which is very good, however the column headers (1-10, 11-20, 21-30) are redundant and just take up space. Imo they should be removed.

2.

All emojis in the page are currently in this format: `ORDER. USED x EMOJI` e.g. `1. 73 x :forteohno:` this can make emojis not aligned.I propose to change the format so that all emoji are aligned (top to bottom).

There are multiple possible formats but one that comes to mind is: `FILLED_ORDER. EMOJI x USED` e.g. `1 . :forteohno: x 73` (notice the space after 1). To keep things compatible with all command usage outputs the number of spaces to fill should be the highest number of ORDER digits that the **current** page has.

For example if we have 13 pages with a total of 300 emojis we do not need to pad the first page with 3 if the first page doesn't display 3 digits ORDER numbers, but 2 because it display up to 2 ORDER numbers. Only on pages where 3 digit ORDER numbers are seen should we fill with 3 space.

This prevents first pages having lot of fills if we end up with thousand of emoji,fill should only be done in the context of the current page, so every emoji is aligned.

**Comment by HuyaneMatsu** [comment]
> When used on specific user emojis will be shown in columns, which is very good, however the column headers (1-10, 11-20, 21-30) are redundant and just take up space. Imo they should be removed.

Those are embed fields and they must have something as their "name". Both `field.name` and `field.value` are required fields.

> All emojis in the page are currently in this format: ORDER. USED x EMOJI e.g. 1. 73 x :forteohno: this can make emojis not aligned.I propose to change the format so that all emoji are aligned (top to bottom).
>
> There are multiple possible formats but one that comes to mind is: FILLED_ORDER. EMOJI x USED e.g. 1 . :forteohno: x 73 (notice the space after 1). To keep things compatible with all command usage outputs the number of spaces to fill should be the highest number of ORDER digits that the current page has.

Since each character has different length, doing `1 . :forteohno: x 73` would not resolve the issue. The emoji  need to be first if you would want to align it perfectly.

**Comment by HuyaneMatsu** [comment]
Preview of the new version is out on 1 command. Please place your bets.

**Comment by HuyaneMatsu** [comment]
All commands are using the new style now. Closing.
