### ISSUE TITLE
Allow to target multiple users with commands like /hug

### ISSUE THREAD

**Issue by UnconsciousPebble** [HuyaneMatsu/Koishi#33]
Allow to target multiple users with commands like /hug by mentioning their usernames and those members getting pinged by Koishi.

**Comment by HuyaneMatsu** [comment]
Max amount of targeted users?

**Comment by UnconsciousPebble** [comment]
Like 5, or add a rate limit to prevent spam.

**Comment by HuyaneMatsu** [comment]
So 25 👌🏻

**Comment by HuyaneMatsu** [comment]
Multi-user part done. Rate limit not yet.

**Comment by HuyaneMatsu** [comment]
Added 🚀
