### ISSUE TITLE
/unban and /unkick commands

### ISSUE THREAD

**Issue by UnconsciousPebble** [HuyaneMatsu/Koishi#36]
Add a command to ping a member who was kicked or banned with an invitation link, a cute Koishi pic and a welcome back message with a selectable response like "kicked by mistake, pwease come back!" and optionally custom explanation.

**Comment by HuyaneMatsu** [comment]
There is no such a thing as "unkick". :KoishiDerp:

**Comment by HuyaneMatsu** [comment]
To avoid abuse it will check audit logs for the kick / ban event. And will have a short regret period.

**Comment by HuyaneMatsu** [comment]
There will be an another `/un-ban` and an `un-mute` command. This one will be called `/regret-ban` and `/regret-kick`.

**Comment by HuyaneMatsu** [comment]
Added, will be alive next restart 🚀
