### ISSUE TITLE
Touhou feeds for regular channels

### ISSUE THREAD

**Issue by UnconsciousPebble** [HuyaneMatsu/Koishi#40]
Please port the new Touhou character feed function to regular channels in addition to just forum channels.
This would be great because regular channels can have icons setup and can be individually re-arranged (into categories or reordered within a category) and also work with the emoji-copy function, which is very useful and innovative!
Would putting #tags of the characters into the target channels, maybe along with some trigger emote in the name or description work?

**Comment by HuyaneMatsu** [comment]
Pushed. Will be alive on next restart.
