### ISSUE TITLE
Ban easter egg

### ISSUE THREAD

**Issue by HuyaneMatsu** [HuyaneMatsu/Koishi#43]
If someone bans the 6th person within one week, the following image should show up:

![](https://cdn.discordapp.com/attachments/445191707491958784/1033674494939766814/orin-body-collecting-meme-0000.jpg)

**Comment by ShinyKoishi** [comment]
Koishi is orin realll

**Comment by HuyaneMatsu** [comment]
Added, will be alive next restart 🚀
