### ISSUE TITLE
Dynamic Command Mentioning Feature

### ISSUE THREAD

**Issue by HimeEsuto** [HuyaneMatsu/Koishi#47]
Add a support for mentioning static commands; a dynamic command mentioning feature as you put it. I would like to see support for a dynamic command's mention.

**Comment by HuyaneMatsu** [comment]
Please rename the title to the feature you desire. And put into the description that you want to see. If you have library related request then please open an issue about in that's respective repository.

**Comment by HuyaneMatsu** [comment]
Pushed. Will be alive on next restart.
