### ISSUE TITLE
Suggestion: Image generation

### ISSUE THREAD

**Issue by unfortunatelyalex** [HuyaneMatsu/Koishi#48]
This might be a pretty common suggestion nowadays but there are some people who can't run Stable Diffusion on their system or don't have access to DALL-E 2.

A command can look like this
/(dream/imagine/generate) prompt:absurdres highres, 1girl, koishi komeiji, smile, light blush, headshot, looking_at_viewer, solo, hat, officials art, tone mapping, high resolution, fine, visible face, dark green eyes, short green hair, human ears, hyperrealistic, short hair, smooth skin, 3d graphics, detailed, visible face, head tilt, cinematic lighting, outdoor, perfect face, best quality, detailed eyes, lighting, hetercromia hands on hip, japanese clothes, kawaii, detailed, 8 k, perfect body, symmetrical face, detailed pupils, perfect face, perfect eyes, detailed clothes, focused on the face, detailed, photo realistic height:512 width:512 guidance_scale:7.0 steps:30 sampler:k_euler_a seed:3750737201

Height and width will be 512 if not set, seed will be random if not set

[This is how the result of that prompt looks like](https://cdn.discordapp.com/attachments/1039816902459011092/1040172139359256586/3750737201.png)

I have no idea how to describe what options there are to the command so if you want to look for yourself
![grafik](https://user-images.githubusercontent.com/61123283/201033160-c939ce0b-1ca9-49ca-b6bc-b356c161ced1.png)
https://github.com/harubaru/discord-stable-diffusion

If you want to join their discord server (which is also a touhou based server) I can gladly send you an invite link

**Comment by HuyaneMatsu** [comment]
I get this suggestion every day from @UnconsciousPebble.

I do not plan to add processing heavy commands into Koishi. Instead I want to focus on smart ones. (yes Koishi is smart)

Koishi is also not hosted on cripto mine, but on a web app host. So it is technically impossible to execute these in reasonable time.
