### ISSUE TITLE
[KU] Automatic pushing up of voice channels during a stream

### ISSUE THREAD

**Issue by UnconsciousPebble** [HuyaneMatsu/Koishi#49]
Automatically push up a voice channel (select channel with emote/tag) to the top of the channel list as soon as a member (non-bot) starts a stream and return them to their original position once the stream ends (with a short delay to account for disconnects).
The idea is to attract attention to members streaming automatically, without cluttering the top of the channel list with ununused voice channels.

**Comment by HuyaneMatsu** [comment]
Added 🚀
