### ISSUE TITLE
Add multiple character search syntaxis to the touhou-feed command

### ISSUE THREAD

**Issue by UnconsciousPebble** [HuyaneMatsu/Koishi#51]
Add the ability to search and randomly post combinations of characters together, like "#koishi+flandre" and "#koishi+satori" in one channel would poll an image with Koishi **and** Flandre **or** Koishi **and** Satori randomly (instead of images with only Koishi, Flandre and Satori together in one image). Also possibly select randomly among a combined character tag like  "#koishi+satori" and a solo character tag "#koishi+solo"

**Comment by HuyaneMatsu** [comment]
Added 🚀
