### ISSUE TITLE
[KU] Add a condition to push up voice channels when X number of users join

### ISSUE THREAD

**Issue by UnconsciousPebble** [HuyaneMatsu/Koishi#52]
Add a condition to the voice channel push up function to trigger when X number of users join a channel.
Ideally, it should be possible to set that number, but a hard coded value like 2 or 3 (including bots) should work.

**Comment by HuyaneMatsu** [comment]
Conditions:
1 bot + 1 user
2 user
1 user streaming

Extra:
Include Radio channels

**Comment by UnconsciousPebble** [comment]
Just 2 users present in a voice channel is fine, for when a bot streams music.

**Comment by HuyaneMatsu** [comment]
Added 🚀
