### ISSUE TITLE
self-ban and self-kick

### ISSUE THREAD

**Issue by HuyaneMatsu** [HuyaneMatsu/Koishi#54]
Add `/self-ban` and `/self-kick` commands.

Since Koishi is already at a limit, creating a new `self` main command and then having `mute`, `ban` and `kick` sub-commands would be the best solution.

> "masochist sure are something"

**Comment by ShinyKoishi** [comment]
Hmmmmmmmmm~ Well it's a good idea but maybe some restrictions on the ban and kick command? like need some warning to **Fuck over the masochist**

**Comment by HuyaneMatsu** [comment]
I will add a confirmation form, so they can type a reason why they want to be banned.

**Comment by ShinyKoishi** [comment]
>Add confirmation form
>**MASOCHISMMMMMMMMMMM**

**Comment by HuyaneMatsu** [comment]
Added, will be alive next restart 🚀
