### ISSUE TITLE
Divorce partner that deleted their acccount

### ISSUE THREAD

**Issue by ShinyKoishi** [HuyaneMatsu/Koishi#70]
one of my friend has an issue where she can't divorce her partner who is deleted user.

**Comment by HuyaneMatsu** [comment]
Divorce will be changed to use user auto completion. The same logic will be added to reject proposal, cancel proposal and to accept proposal commands as well. This means the command will not only list who you can divorce, but will also support deleted users as well. :KoishiNice:

**Comment by HuyaneMatsu** [comment]
Has been added :KoishiNice:
