### ISSUE TITLE
Add the option to let the bot Dm the user to vote the bot when avaible

### ISSUE THREAD

**Issue by ShinyKoishi** [HuyaneMatsu/Koishi#73]
Title says it all~ But just in case

What I mean is just an option in the bot setting like a 'vote setting' for the bot to dm the user that says they can vote the bot now.

**Comment by HuyaneMatsu** [comment]
top.gg has a builtin option for this. Why would Koishi also have an option for it?

**Comment by HuyaneMatsu** [comment]
Since top.gg has this feature and I got no reply, closing the issue.
