### ISSUE TITLE
Add a "say hi to new user" button to the welcoming feature

### ISSUE THREAD

**Issue by UnconsciousPebble** [HuyaneMatsu/Koishi#74]
Add a "say hi to new user" button to the welcoming feature that members can click on and which will ping the new person with a greeting and a random Koishi picture to replicate the default Discord feature that does the same, so the default one can be turned off.
Reason: More people will use it since it's easy to click a button and there will be more Koishi images posted and more interactions with the bot in total and it will make the bot stand out more among similar bots with greeting features.

**Comment by HuyaneMatsu** [comment]
Added.
