### ISSUE TITLE
Asset copyright information for the *ex plugin

### ISSUE THREAD

**Issue by albertopoljak** [HuyaneMatsu/Koishi#75]
As per discussion in Discord, I took a quick look to see if I could find source for some assets.

For this asset:
koishi/plugins/sex/assets/chiruno-probably-sex.gif

Source is Fantasy Kaleidoscope ~The Memories of Phantasm
You can confirm it by looking up "Touhou Memories of Phantasm Cirno Moments" on Youtube.

Additionally, pretty sure the same source is for these as well (didn't completely confirm):
koishi/plugins/sex/assets/chiruno-maybe-sex.gif
koishi/plugins/sex/assets/chiruno-no-sex.gif
koishi/plugins/sex/assets/chiruno-yes-sex-fast.gif
koishi/plugins/sex/assets/chiruno-yes-sex.gif

**Comment by HuyaneMatsu** [comment]
Added information for `chiruno-probably-sex.gif`. If you can confirm the rest, will add them as well.
