### ISSUE TITLE
Bugged user waifu stats and marriage costs

### ISSUE THREAD

**Issue by UnconsciousPebble** [HuyaneMatsu/Koishi#76]
Bugged user waifu stats and marriage costs see below...
![c0464462-f8a7-4647-af37-d5d7b79166fa](https://github.com/user-attachments/assets/5e4ccee7-8c09-4a5f-821e-7cc0659457b4)
![d51438b4-6fb1-4662-837a-cdb348e69435](https://github.com/user-attachments/assets/788a863c-bffe-4f47-b344-5863c9e28d41)

**Comment by HuyaneMatsu** [comment]
They abused a `/21` bug and after noticed I reset their hearts & waifu stats. Turns out the stats were incorrectly reset.

Now reset the stats correctly and also the waifu cost.
