### ISSUE TITLE
Add a button to reciprocate a user like /hug

### ISSUE THREAD

**Issue by UnconsciousPebble** [HuyaneMatsu/Koishi#77]
Add a button to reciprocate a user like /hug that only the user who was targeted by it can use and which would do the same as manually replying with "hug", see example from other user installed bot: 
![image](https://github.com/user-attachments/assets/061265b4-230e-4cf6-b453-c34b78db291e)

**Comment by HuyaneMatsu** [comment]
This would just make the message that already takes a lot of space more space, which is not great.
As you also mentioned this can be already done without the button, which makes this feature request obsolete.

Closing.
