### ISSUE TITLE
k!loop or /loop command

### ISSUE THREAD

**Issue by HimeEsuto** [HuyaneMatsu/Koishi#8]
If the bot detects itself playing some kind of audio in the background when the command is used, it will endlessly repeat that specific audio until something like k!stoploop or /stoploop is used, telling the bot to disconnect can work as well. If it isn't playing anything, it will give an error.

**Comment by HuyaneMatsu** [comment]
Pat, pat Esuto.

Will be added in 1 week. :ok_hand:

**Comment by HuyaneMatsu** [comment]
Added:
- `/loop`
- `/loop-all` (extra)
- `/loop-stop`
